const routes = {
    page: '?page=',
    dashboard: '/',
    notFound: '*',
    report: '/bao-cao',
    add: '/them',
    update: '/sua',
    delete: '/xoa',
    vaccine: '/vaccine',
    conditionPromotion: '/dieu-kien-khuyen-mai',
    typeOfVaccine: '/loai-vaccine',
    customer: '/khach-hang',
    customerType: '/loai-khach-hang',
    permission: '/chuc-vu',
    staff: '/nhan-vien',
    supplier: '/nha-cung-cap',
    shipment: '/lo-vaccine',
    vaccinePrice: '/gia-vaccine',
    vaccinePackage: '/goi-vaccine',
    regulationCustomer: '/quy-dinh-khach-hang',
    screeningExamination: '/kham-san-loc',
    paymentMethod: '/hinh-thuc-thanh-toan',
    pay: '/thanh-toan',
    injectionSchedule: '/lich-tiem',
    injectionIncident: '/su-co-tiem',
    regulationInjection: '/quy-dinh-tiem',
    customerRank: '/xep-loai-khach-hang',
    customerRankDetail: '/chi-tiet-xep-loai-khach-hang',
    order: '/don-dat-hang',
    entrySlip: '/phieu-nhap',
    promotion: '/khuyen-mai',
    auth: '/dang-nhap',
    account: '/tai-khoan',
    loginSession: '/phien-dang-nhap',
    statistical: '/thong-ke',
    permissionDetail: '/phan-quyen',
};
export default routes;
