const namePages = {
    AdditionalCustomerInformation: { name: 'AdditionalCustomerInformation', text: 'Thông tin bổ sung khách hàng' },
    Auth: { name: 'Auth', text: 'Auth' },
    Banner: { name: 'Banner', text: 'Banner' },
    Cart: { name: 'Cart', text: 'Giỏ hàng' },
    ConditionPromotion: { name: 'ConditionPromotion', text: 'Điều kiện khuyến mãi' },
    Customer: { name: 'Customer', text: 'Khách hàng' },
    CustomerRank: { name: 'CustomerRank', text: 'Xếp loại khách hàng' },
    CustomerRankDetail: { name: 'CustomerRankDetail', text: 'Chi tiết xếp loại khách hàng' },
    CustomerType: { name: 'CustomerType', text: 'Loại khách hàng' },
    EntrySlip: { name: 'EntrySlip', text: 'Nhập hàng' },
    EntrySlipDetail: { name: 'EntrySlipDetail', text: 'Chi tiết phiếu nhập' },
    Order: { name: 'Order', text: 'Đặt hàng' },
    OrderDetail: { name: 'OrderDetail', text: 'Chi tiết phiếu đặt' },
    InjectionIncident: { name: 'InjectionIncident', text: 'Sự cố tiêm' },
    InjectionSchedule: { name: 'InjectionSchedule', text: 'Lịch tiêm' },
    InjectionScheduleDetail: { name: 'InjectionScheduleDetail', text: 'Chi tiết lịch tiêm' },
    Login: { name: 'Login', text: 'Tài khoản' },
    LoginSession: { name: 'LoginSession', text: 'Phiên đăng nhập' },
    Notification: { name: 'Notification', text: 'Thông báo' },
    Pay: { name: 'Pay', text: 'Thanh toán' },
    PayDetail: { name: 'PayDetail', text: 'Chi tiết thanh toán' },
    PaymentMethod: { name: 'PaymentMethod', text: 'Phương thức thanh toán' },
    Permission: { name: 'Permission', text: 'Chức vụ' },
    PermissionDetails: { name: 'PermissionDetails', text: 'Phân quyền' },
    Promotion: { name: 'Promotion', text: 'Khuyến mãi' },
    RegulationCustomer: { name: 'RegulationCustomer', text: 'Quy định khách hàng' },
    RegulationInjection: { name: 'RegulationInjection', text: 'Quy định tiêm' },
    ScreeningExamination: { name: 'ScreeningExamination', text: 'Khám sàn lọc' },
    Shipment: { name: 'Shipment', text: 'Lô vacine' },
    Staff: { name: 'Staff', text: 'Nhân viên' },
    Statistical: { name: 'Statistical', text: 'Thống kê' },
    Supplier: { name: 'Supplier', text: 'Nhà cung cấp' },
    TypeOfVaccine: { name: 'TypeOfVaccine', text: 'Loại vaccine' },
    Upload: { name: 'Upload', text: 'Upload' },
    Vaccine: { name: 'Vaccine', text: 'Vaccine' },
    VaccinePackage: { name: 'VaccinePackage', text: 'Gói vaccine' },
    VaccinePackageDetail: { name: 'VaccinePackageDetail', text: 'Chi tiết gói vaccine' },
    VaccinePrice: { name: 'VaccinePrice', text: 'Giá vaccine' },
};
export default namePages;
